

--	DROP TRIGGER	TST_JOHN_TRIG1;


	CREATE OR REPLACE TRIGGER 	TST_JOHN_TRIG1	
	BEFORE 	UPDATE  
	ON 		TST_JOHN1 	
	FOR EACH ROW
	WHEN (OLD.ADDR_COMPRESS IS NULL)

--	DECLARE
--		DUMMY		NUMBER;

	BEGIN

--	>>>	DO NOT MODIFY THE TARGET TABLE WITH SQL UPDATE
--	>>>	MODIFY THE TARGET TABLE USING	:NEW.

--		IF	:OLD.ADDR_SOUNDEX IS NULL		THEN
--			UPDATE TST_JOHN1
--			SET	 ADDR_SOUNDEX = SOUNDEX (ADDR_NAME);
--		END IF;
	
		
		:NEW.ADDR_COMPRESS	:= ADR_COMPRESS_NAME (:OLD.ADDR_NAME, '');

		:NEW.ADDR_SFX		:= 'X';

	END;




	CREATE OR REPLACE TRIGGER 	TST_JOHN_TRIG2	
	BEFORE 	UPDATE  OR INSERT 
	ON 		TST_JOHN1 	
	FOR EACH ROW

	BEGIN

		IF	UPDATING
		AND	:OLD.ADDR_SOUNDEX IS NULL		THEN
			:NEW.ADDR_SOUNDEX		:= SOUNDEX (:OLD.ADDR_NAME);
		END IF;
		
		:NEW.ADDR_ENDING		:= 'THATS ALL FOLKS';

	END;





