# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# 1.py
# Created on: 2019-08-06 09:41:44.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: 1 <fileName> <DBS_Name> <Data_type> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Script arguments
fileName = arcpy.GetParameterAsText(0)
if fileName == '#' or not fileName:
    fileName = "BASE" # provide a default value if unspecified

DBS_Name = arcpy.GetParameterAsText(1)
if DBS_Name == '#' or not DBS_Name:
    DBS_Name = "GIS" # provide a default value if unspecified

Data_type = arcpy.GetParameterAsText(2)
if Data_type == '#' or not Data_type:
    Data_type = "FeatureDataset" # provide a default value if unspecified

# Local variables:
SaveAs = "C:\\Users\\hchen\\AppData\\Roaming\\ESRI\\Desktop10.7\\conncections\\schemaUserConnection\\%DBS_Name%.sde\\%DBS_Name%.%DBS_Name%.%fileName%"
GIS__fileName_ = "Database Connections\\z-gis@geoprod1.sde\\GIS.%fileName%"
v_SaveAs_ = "%SaveAs%"

# Process: Copy (2)
arcpy.Copy_management(GIS__fileName_, v_SaveAs_, Data_type)

