# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# 1.py
# Created on: 2019-07-30 12:44:46.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: 1 <RoleValue> <ACTIVATE_VALUE> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Load required toolboxes
arcpy.ImportToolbox("Model Functions")

# Script arguments
RoleValue = arcpy.GetParameterAsText(0)
if RoleValue == '#' or not RoleValue:
    RoleValue = "GIS_ED" # provide a default value if unspecified

ACTIVATE_VALUE = arcpy.GetParameterAsText(1)
if ACTIVATE_VALUE == '#' or not ACTIVATE_VALUE:
    ACTIVATE_VALUE = "1" # provide a default value if unspecified

# Local variables:
UserList = "X:\\GIS_Analysts\\HCHEN\\0 Setup new server and SQL server\\data.mdb\\UserList"
filter_on_User_List_table = "[ACTIVATE]= %ACTIVATE_VALUE% AND [Role] = '%RoleValue%'"
QueryTable = "QueryTable"
Value = QueryTable

# Process: Make Query Table
arcpy.MakeQueryTable_management("'X:\\GIS_Analysts\\HCHEN\\0 Setup new server and SQL server\\data.mdb\\UserList'", QueryTable, "NO_KEY_FIELD", "UserList.LOGINNAME", "UserList.Role #;UserList.LOGINNAME #;UserList.ACTIVATE #", filter_on_User_List_table)

# Process: Iterate Field Values
arcpy.IterateFieldValues_mb(QueryTable, "LOGINNAME", "String", "true", "true", "")

