


	CREATE TABLE	TMP_HEALTH
	(
		BUSI_NAME			VARCHAR2(40),
		ADDR_NUM			NUMBER(06),
		ADDR_PFX			VARCHAR2(02),
		ADDR_NAME			VARCHAR2(40),
		ADDR_TYPE			VARCHAR2(04),
		ADDR_SFX			VARCHAR2(02),
		UNIT_TYPE			VARCHAR2(10),
		UNIT_NUM			VARCHAR2(20)
	);
	