	set echo off;
	
	SELECT 'dba_users', USERNAME, TEMPORARY_TABLESPACE 
	FROM DBA_USERS
	WHERE		TEMPORARY_TABLESPACE = ''
--	WHERE		DEFAULT_TABLESPACE = ''
	;


	SELECT 'dba_tablespaces', TABLESPACE_NAME, MAX_EXTENTS
	FROM 		DBA_TABLESPACES
	WHERE		TABLESPACE_NAME = 'GIS_DATA'
	;


	SELECT	'dba_data_files', TABLESPACE_NAME, COUNT(*), SUM(BYTES)
	FROM		DBA_DATA_FILES
	WHERE		TABLESPACE_NAME = 'GIS_DATA'
	;


	SELECT	'dba_extents', TABLESPACE_NAME, COUNT(*), SUM(BYTES)
	FROM		DBA_EXTENTS
	WHERE		TABLESPACE_NAME = 'GIS_DATA'
	;


	SELECT	'dba_free_space', TABLESPACE_NAME, COUNT(*), SUM(BYTES)
	FROM		DBA_FREE_SPACE
	WHERE		TABLESPACE_NAME = 'GIS_DATA'
	;


	SELECT	'dba_free_space_coalesced', TABLESPACE_NAME, COUNT(*), SUM (TOTAL_EXTENTS), 
		SUM(EXTENTS_COALESCED), SUM(TOTAL_BYTES), SUM(BYTES_COALESCED)
	FROM		DBA_FREE_SPACE_COALESCED
	WHERE		TABLESPACE_NAME = 'GIS_DATA'
	;

