select INDEX_NAME, TABLE_NAME, UNIQUENESS
from  dba_indexes 
where dba_indexes.TABLE_owner='GIS'
and TABLE_NAME not like 'A0%' 
and TABLE_NAME not like 'A1%' 
and TABLE_NAME not like 'A2%' 
and TABLE_NAME not like 'A3%' 
and TABLE_NAME not like 'A4%' 
and TABLE_NAME not like 'A5%' 
and TABLE_NAME not like 'A6%' 
and TABLE_NAME not like 'A7%' 
and TABLE_NAME not like 'A8%' 
and TABLE_NAME not like 'A9%' 
and TABLE_NAME not like 'D0%' 
and TABLE_NAME not like 'D1%' 
and TABLE_NAME not like 'D2%' 
and TABLE_NAME not like 'D3%' 
and TABLE_NAME not like 'D4%' 
and TABLE_NAME not like 'D5%' 
and TABLE_NAME not like 'D6%' 
and TABLE_NAME not like 'D7%' 
and TABLE_NAME not like 'D8%' 
and TABLE_NAME not like 'D9%' 
and TABLE_NAME not like 'S0%' 
and TABLE_NAME not like 'S1%' 
and TABLE_NAME not like 'S2%' 
and TABLE_NAME not like 'S3%' 
and TABLE_NAME not like 'S4%' 
and TABLE_NAME not like 'S5%' 
and TABLE_NAME not like 'S6%' 
and TABLE_NAME not like 'S7%' 
and TABLE_NAME not like 'S8%' 
and TABLE_NAME not like 'S9%' 
ORDER BY TABLE_NAME;