
--	C:\ORANT\SCRIPTS\VERIFY\ADR_SIMULAR.sql

--	CALCULATE PERMUTEITY CODE FOR PERMUTATIONS OF STREET NUMBER
--	ALLOWS MATCH ON STEET NUMBER WITH TRANSPOSED DIGITS



CREATE OR REPLACE FUNCTION	garland.ADR_PERMUTE_NUMBER

	(	USER_NUMB	IN 	NUMBER	)	--  STREET NUMBER	

		RETURN		NUMBER		--  PERMUTE CODE			

AS
		PERMUTE_NUMB	VARCHAR2(20);

		PERMUTE_LENG	NUMBER		:= 0;
		PERMUTE_CODE	NUMBER		:= 0;

		X			NUMBER(02)		:= 0;
		FACTOR		NUMBER(04)		:= 0;

	BEGIN

		PERMUTE_NUMB	:= LTRIM (TO_CHAR (USER_NUMB, '999999'));
		PERMUTE_LENG	:= LENGTH (PERMUTE_NUMB);

		PERMUTE_CODE	:= 01;

		FOR	X  IN   01..PERMUTE_LENG
		LOOP
			SELECT DECODE ( SUBSTR (PERMUTE_NUMB, X, 01),

				'2',		02,
				'3',		03,
				'5',		05,
				'7',		07,

				'0',		11,
				'1',		13,
				'4',		17,
				'6',		19,
				'8',		23,
				'9',		29,

						01)	

			INTO FACTOR		FROM DUAL;

			PERMUTE_CODE :=  PERMUTE_CODE * FACTOR;

		END LOOP;

		RETURN	PERMUTE_CODE;

	END	ADR_PERMUTE_NUMBER;



--	=======================================================


/*

	SELECT
		ADR_PERMUTE_STREET_NUMBER  (1234),	
		ADR_PERMUTE_STREET_NUMBER  (2341),	
		ADR_PERMUTE_STREET_NUMBER  (3412),	
		ADR_PERMUTE_STREET_NUMBER  (4321)	

	FROM	DUAL;

*/
