rhyme             1
rhyme.            1
trans             1
LIKE              2
NUM               2
more              3
more.             3
mores             3
mores.            3
pcut              4
pflip             4
pflip.            4
pulls             4
pulls.            4
sflip             4
sflip.            4
sflip;            4
plur              5
plur;             5
mixed             6
mixed.            6
mixed;            6
part              6
part.             6
AVE               7
AVE.              7
MISC              7
MISC.             7
NTH               7
NTH$              7
PART              7
PAST              7
PULL              7
PULL.             7
ppull             8
ppull.            8
ppull;            8
ppush             8
pull              8
pull;             8
spull             8
spull.            8
spush             8
tpull             8
tpull.            8
tpull;            8
tpush             8
22$               9
22/               9
23                9
23$               9
asis              9
asis.             9
