
	create garland.CDRELADR
(
PARCEL_ID                               VARCHAR2(11)
ADDR_ID                                 NUMBER(8)
ADDR_NUM                                NUMBER(6)
ADDR_PFX                                VARCHAR2(2)
ADDR_NAME                               VARCHAR2(20)
ADDR_TYPE                               VARCHAR2(4)
ADDR_SFX                                VARCHAR2(2)
ADDR_BLDG                               VARCHAR2(20)
UNIT_TYPE                               VARCHAR2(20)
UNIT_NUM                                VARCHAR2(20)
ZIP_CODE                                NUMBER(5)
ZIP_PLUS                                NUMBER(4)
ADDR_STATUS                             VARCHAR2(3)
MAP_GRID                                NUMBER(5)
UNIT_AUX                                VARCHAR2(20)
MSLINK                                  NUMBER(6)
MAPID                                   NUMBER(4)
PRIVATE_STR                             VARCHAR2(3)
X_COORD                                 NUMBER(38,8)
Y_COORD                                 NUMBER(38,8)
TAX_KEY                                 NUMBER(8)
UMS_KEY                                 NUMBER(8)
PARCELID                                NUMBER(8)
ADDRESS_LABEL                           VARCHAR2(50)
)
