
--	GENERATED BY SQL LOADER 
--	SEE \\LOADER\VERIZON 


	create or replace view  garland.temp_view		AS
(
	select
		item01	phone,		

		item02	addrnum,	
		item03	addrpfx,	
		item04	addrname,	
		item05	addrtype,	
		item06	addrsfx,	

		item07	city,		
		item08	state,		

		item09	addrunit,		

		item10	customer,	
		item11	main		

	from	garland.GIS_Objects
);
