--	=====================================================================
set echo		off;
set linesize	2000;
set pagesize	9999;
set sqlblanklines	on;
set timing		off;
set serveroutput	on	size 99999;
--  alter session set nls_date_format = 'yyyy-mm-dd hh24:mi:ss';  
--	=====================================================================

-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
--drop   table GARLAND.CCS_ADDRESS;
  create table GARLAND.CCS_ADDRESS  (
  ADDRESS_ID                        NUMBER(8,0)
 ,ADDR_BLOCK                        NUMBER(8,0)
 ,ADDR_NUMBER                       NUMBER(8,0)
 ,ADDR_PREFIX                       VARCHAR2(2)
 ,ADDR_NAME                         VARCHAR2(30)
 ,ADDR_TYPE                         VARCHAR2(4)
 ,ADDR_SUFFIX                       VARCHAR2(2)
 ,ADDR_BLDG                         VARCHAR2(20)
 ,ADDR_UNIT                         VARCHAR2(20)
 ,ADDR_CITY                         VARCHAR2(15)
 ,ADDR_ZIP                          VARCHAR2(5)
 ,ADDR_TEN_CODE                     VARCHAR2(4)
 ,COUNCIL_DIST                      VARCHAR2(1)
 ,INSPECTOR_DIST                    VARCHAR2(2)
 ,POLICE_BEAT                       NUMBER(3,0)
 ,TAX_ACCOUNT                       VARCHAR2(25)
 ,TAX_DCAD                          VARCHAR2(25)
 ,TAX_PROP_TYPE                     VARCHAR2(1)
 ,TAX_ZONING_CODE                   VARCHAR2(10)
 ,TAX_EXEMPTION                     VARCHAR2(12)
 ,TAX_DEED_CHNG_DATE                VARCHAR2(10)
 ,TAX_OWNER                         VARCHAR2(100)
 ,TAX_ADDR1                         VARCHAR2(50)
 ,TAX_ADDR2                         VARCHAR2(50)
 ,TAX_CITY                          VARCHAR2(30)
 ,TAX_STATE                         VARCHAR2(2)
 ,TAX_ZIP                           VARCHAR2(5)
 ,TAX_TEN_CODE                      VARCHAR2(4)
 ,TAX_OCCUPIED                      VARCHAR2(1)
 ,TAX_LEGAL_DESC                    VARCHAR2(200)
 ,UMS_LAST_NAME                     VARCHAR2(40)
 ,UMS_FIRST_NAME                    VARCHAR2(40)
 ,UMS_DRIVERS_LIC                   VARCHAR2(20)
 ,UMS_BIRTH_DATE                    VARCHAR2(10)
 ,INTERSECTION1                     VARCHAR2(40)
 ,INTERSECTION2                     VARCHAR2(40)
 ,PARCEL_ID                         VARCHAR2(11)
 ,STREET_ID                         VARCHAR2(6)
 ,BLOCK_ID                          NUMBER(10,0)
 ,ROAD_ID                           NUMBER(8,0)
 ,INTERSECT_ID1                     VARCHAR2(20)
 ,INTERSECT_ID2                     VARCHAR2(20)
 ,TAX_ID                            VARCHAR2(25)
 ,UMS_ID                            NUMBER(8,0)
 ,RECORD_SEQ                        NUMBER(10,0)
 ,PARCEL_ID_NEW                     NUMBER(8,0)
  )  tablespace GIS_DATA  nologging
  ;

--drop   table GARLAND.CCS_ADDRESSES;
  create table GARLAND.CCS_ADDRESSES  (
  ADDRESS_ID                        NUMBER(8,0)
 ,ADDR_BLOCK                        NUMBER(8,0)
 ,ADDR_NUMBER                       NUMBER(8,0)
 ,ADDR_PREFIX                       VARCHAR2(2)
 ,ADDR_NAME                         VARCHAR2(30)
 ,ADDR_TYPE                         VARCHAR2(4)
 ,ADDR_SUFFIX                       VARCHAR2(2)
 ,ADDR_BLDG                         VARCHAR2(20)
 ,ADDR_UNIT                         VARCHAR2(20)
 ,ADDR_CITY                         VARCHAR2(15)
 ,ADDR_ZIP                          VARCHAR2(5)
 ,ADDR_TEN_CODE                     VARCHAR2(4)
 ,COUNCIL_DIST                      VARCHAR2(1)
 ,INSPECTOR_DIST                    VARCHAR2(2)
 ,POLICE_BEAT                       NUMBER(3,0)
 ,TAX_ACCOUNT                       VARCHAR2(25)
 ,TAX_DCAD                          VARCHAR2(25)
 ,TAX_PROP_TYPE                     VARCHAR2(1)
 ,TAX_ZONING_CODE                   VARCHAR2(10)
 ,TAX_EXEMPTION                     VARCHAR2(12)
 ,TAX_DEED_CHNG_DATE                VARCHAR2(10)
 ,TAX_OWNER                         VARCHAR2(100)
 ,TAX_ADDR1                         VARCHAR2(50)
 ,TAX_ADDR2                         VARCHAR2(50)
 ,TAX_CITY                          VARCHAR2(30)
 ,TAX_STATE                         VARCHAR2(2)
 ,TAX_ZIP                           VARCHAR2(5)
 ,TAX_TEN_CODE                      VARCHAR2(4)
 ,TAX_OCCUPIED                      VARCHAR2(1)
 ,TAX_LEGAL_DESC                    VARCHAR2(200)
 ,UMS_LAST_NAME                     VARCHAR2(40)
 ,UMS_FIRST_NAME                    VARCHAR2(40)
 ,UMS_DRIVERS_LIC                   VARCHAR2(20)
 ,UMS_BIRTH_DATE                    VARCHAR2(10)
 ,INTERSECTION1                     VARCHAR2(40)
 ,INTERSECTION2                     VARCHAR2(40)
 ,PARCEL_ID                         VARCHAR2(11)
 ,STREET_ID                         VARCHAR2(6)
 ,BLOCK_ID                          NUMBER(10,0)
 ,ROAD_ID                           NUMBER(8,0)
 ,INTERSECT_ID1                     VARCHAR2(20)
 ,INTERSECT_ID2                     VARCHAR2(20)
 ,TAX_ID                            VARCHAR2(25)
 ,UMS_ID                            NUMBER(8,0)
 ,RECORD_SEQ                        NUMBER(10,0)
  )  tablespace GIS_DATA  nologging
  ;

--drop   table GARLAND.CCS_ADDRESSESS;
  create table GARLAND.CCS_ADDRESSESS  (
  ADDRESS_ID                        UNDEFINED(0)
 ,ADDR_BLOCK                        UNDEFINED(0)
 ,ADDR_NUMBER                       UNDEFINED(0)
 ,ADDR_PREFIX                       UNDEFINED(0)
 ,ADDR_NAME                         UNDEFINED(0)
 ,ADDR_TYPE                         UNDEFINED(0)
 ,ADDR_SUFFIX                       UNDEFINED(0)
 ,ADDR_BLDG                         UNDEFINED(0)
 ,ADDR_UNIT                         UNDEFINED(0)
 ,ADDR_CITY                         UNDEFINED(0)
 ,ADDR_ZIP                          UNDEFINED(0)
 ,ADDR_TEN_CODE                     UNDEFINED(0)
 ,COUNCIL_DIST                      UNDEFINED(0)
 ,INSPECTOR_DIST                    UNDEFINED(0)
 ,POLICE_BEAT                       UNDEFINED(0)
 ,TAX_ACCOUNT                       UNDEFINED(0)
 ,TAX_DCAD                          UNDEFINED(0)
 ,TAX_PROP_TYPE                     UNDEFINED(0)
 ,TAX_ZONING_CODE                   UNDEFINED(0)
 ,TAX_EXEMPTION                     UNDEFINED(0)
 ,TAX_DEED_CHNG_DATE                UNDEFINED(0)
 ,TAX_OWNER                         UNDEFINED(0)
 ,TAX_ADDR1                         UNDEFINED(0)
 ,TAX_ADDR2                         UNDEFINED(0)
 ,TAX_CITY                          UNDEFINED(0)
 ,TAX_STATE                         UNDEFINED(0)
 ,TAX_ZIP                           UNDEFINED(0)
 ,TAX_TEN_CODE                      UNDEFINED(0)
 ,TAX_OCCUPIED                      UNDEFINED(0)
 ,TAX_LEGAL_DESC                    UNDEFINED(0)
 ,UMS_LAST_NAME                     UNDEFINED(0)
 ,UMS_FIRST_NAME                    UNDEFINED(0)
 ,UMS_DRIVERS_LIC                   UNDEFINED(0)
 ,UMS_BIRTH_DATE                    UNDEFINED(0)
 ,INTERSECTION1                     UNDEFINED(0)
 ,INTERSECTION2                     UNDEFINED(0)
 ,PARCEL_ID                         UNDEFINED(0)
 ,STREET_ID                         UNDEFINED(0)
 ,BLOCK_ID                          UNDEFINED(0)
 ,ROAD_ID                           UNDEFINED(0)
 ,INTERSECT_ID1                     UNDEFINED(0)
 ,INTERSECT_ID2                     UNDEFINED(0)
 ,TAX_ID                            UNDEFINED(0)
 ,UMS_ID                            UNDEFINED(0)
 ,RECORD_SEQ                        UNDEFINED(0)
  )  tablespace GIS_DATA  nologging
  ;

--drop   table GARLAND.CCS_ADDRESSES_MAKE;
  create table GARLAND.CCS_ADDRESSES_MAKE  (
  ADDRESS_ID                        NUMBER(22)
 ,ADDR_BLOCK                        NUMBER(22)
 ,ADDR_NUMBER                       NUMBER(8,0)
 ,ADDR_PREFIX                       VARCHAR2(2)
 ,ADDR_NAME                         VARCHAR2(30)
 ,ADDR_TYPE                         VARCHAR2(4)
 ,ADDR_SUFFIX                       VARCHAR2(2)
 ,ADDR_BLDG                         VARCHAR2(20)
 ,ADDR_UNIT                         VARCHAR2(20)
 ,ADDR_CITY                         VARCHAR2(13)
 ,ADDR_ZIP                          VARCHAR2(5)
 ,ADDR_TEN_CODE                     VARCHAR2(34)
 ,COUNCIL_DIST                      NUMBER(1,0)
 ,INSPECTOR_DIST                    NUMBER(22)
 ,POLICE_BEAT                       NUMBER(3,0)
 ,TAX_ACCOUNT                       VARCHAR2(10)
 ,TAX_DCAD                          VARCHAR2(25)
 ,TAX_PROP_TYPE                     VARCHAR2(1)
 ,TAX_ZONING_CODE                   VARCHAR2(10)
 ,TAX_EXEMPTION                     VARCHAR2(12)
 ,TAX_DEED_CHNG_DATE                VARCHAR2(10)
 ,TAX_OWNER                         VARCHAR2(81)
 ,TAX_ADDR1                         VARCHAR2(40)
 ,TAX_ADDR2                         VARCHAR2(50)
 ,TAX_CITY                          VARCHAR2(30)
 ,TAX_STATE                         VARCHAR2(2)
 ,TAX_ZIP                           VARCHAR2(5)
 ,TAX_TEN_CODE                      VARCHAR2(4)
 ,TAX_OCCUPIED                      VARCHAR2(1)
 ,TAX_LEGAL_DESC                    VARCHAR2(200)
 ,UMS_LAST_NAME                     VARCHAR2(40)
 ,UMS_FIRST_NAME                    VARCHAR2(40)
 ,UMS_DRIVERS_LIC                   VARCHAR2(20)
 ,UMS_BIRTH_DATE                    VARCHAR2(10)
 ,INTERSECTION1                     VARCHAR2(40)
 ,INTERSECTION2                     VARCHAR2(40)
 ,PARCEL_ID                         VARCHAR2(11)
 ,STREET_ID                         VARCHAR2(0)
 ,BLOCK_ID                          NUMBER(22)
 ,ROAD_ID                           NUMBER(22)
 ,INTERSECT_ID1                     VARCHAR2(20)
 ,INTERSECT_ID2                     VARCHAR2(20)
 ,TAX_ID                            NUMBER(8,0)
 ,UMS_ID                            NUMBER(8,0)
 ,RECORD_SEQ                        NUMBER(22)
 ,PARCEL_ID_NEW                     NUMBER(7,0)
  )  tablespace GIS_DATA  nologging
  ;

--drop   table GARLAND.CCS_ADDRESSES_MAKE_TEST;
  create table GARLAND.CCS_ADDRESSES_MAKE_TEST  (
  ADDRESS_ID                        NUMBER(22)
 ,ADDR_BLOCK                        NUMBER(22)
 ,ADDR_NUMBER                       NUMBER(8,0)
 ,ADDR_PREFIX                       VARCHAR2(2)
 ,ADDR_NAME                         VARCHAR2(30)
 ,ADDR_TYPE                         VARCHAR2(4)
 ,ADDR_SUFFIX                       VARCHAR2(2)
 ,ADDR_BLDG                         VARCHAR2(20)
 ,ADDR_UNIT                         VARCHAR2(20)
 ,ADDR_CITY                         VARCHAR2(13)
 ,ADDR_ZIP                          VARCHAR2(5)
 ,ADDR_TEN_CODE                     VARCHAR2(34)
 ,COUNCIL_DIST                      NUMBER(1,0)
 ,INSPECTOR_DIST                    NUMBER(22)
 ,POLICE_BEAT                       NUMBER(3,0)
 ,TAX_ACCOUNT                       VARCHAR2(10)
 ,TAX_DCAD                          VARCHAR2(25)
 ,TAX_PROP_TYPE                     VARCHAR2(1)
 ,TAX_ZONING_CODE                   VARCHAR2(10)
 ,TAX_EXEMPTION                     VARCHAR2(12)
 ,TAX_DEED_CHNG_DATE                VARCHAR2(10)
 ,TAX_OWNER                         VARCHAR2(81)
 ,TAX_ADDR1                         VARCHAR2(40)
 ,TAX_ADDR2                         VARCHAR2(50)
 ,TAX_CITY                          VARCHAR2(30)
 ,TAX_STATE                         VARCHAR2(2)
 ,TAX_ZIP                           VARCHAR2(5)
 ,TAX_TEN_CODE                      VARCHAR2(4)
 ,TAX_OCCUPIED                      VARCHAR2(1)
 ,TAX_LEGAL_DESC                    VARCHAR2(200)
 ,UMS_LAST_NAME                     VARCHAR2(40)
 ,UMS_FIRST_NAME                    VARCHAR2(40)
 ,UMS_DRIVERS_LIC                   VARCHAR2(20)
 ,UMS_BIRTH_DATE                    VARCHAR2(10)
 ,INTERSECTION1                     VARCHAR2(40)
 ,INTERSECTION2                     VARCHAR2(40)
 ,PARCEL_ID                         VARCHAR2(11)
 ,STREET_ID                         VARCHAR2(0)
 ,BLOCK_ID                          NUMBER(22)
 ,ROAD_ID                           NUMBER(22)
 ,INTERSECT_ID1                     VARCHAR2(20)
 ,INTERSECT_ID2                     VARCHAR2(20)
 ,TAX_ID                            NUMBER(8,0)
 ,UMS_ID                            NUMBER(8,0)
 ,RECORD_SEQ                        NUMBER(22)
 ,PARCEL_ID_NEW                     NUMBER(7,0)
 ,ADDRESS_TYPE                      VARCHAR2(20)
  )  tablespace GIS_DATA  nologging
  ;

--drop   table GARLAND.CCS_ADDRESSES_TEST;
  create table GARLAND.CCS_ADDRESSES_TEST  (
  ADDRESS_ID                        NUMBER(8,0)
 ,ADDR_BLOCK                        NUMBER(8,0)
 ,ADDR_NUMBER                       NUMBER(8,0)
 ,ADDR_PREFIX                       VARCHAR2(2)
 ,ADDR_NAME                         VARCHAR2(30)
 ,ADDR_TYPE                         VARCHAR2(4)
 ,ADDR_SUFFIX                       VARCHAR2(2)
 ,ADDR_BLDG                         VARCHAR2(20)
 ,ADDR_UNIT                         VARCHAR2(20)
 ,ADDR_CITY                         VARCHAR2(15)
 ,ADDR_ZIP                          VARCHAR2(5)
 ,ADDR_TEN_CODE                     VARCHAR2(4)
 ,COUNCIL_DIST                      VARCHAR2(1)
 ,INSPECTOR_DIST                    VARCHAR2(2)
 ,POLICE_BEAT                       NUMBER(3,0)
 ,TAX_ACCOUNT                       VARCHAR2(25)
 ,TAX_DCAD                          VARCHAR2(25)
 ,TAX_PROP_TYPE                     VARCHAR2(1)
 ,TAX_ZONING_CODE                   VARCHAR2(10)
 ,TAX_EXEMPTION                     VARCHAR2(12)
 ,TAX_DEED_CHNG_DATE                VARCHAR2(10)
 ,TAX_OWNER                         VARCHAR2(100)
 ,TAX_ADDR1                         VARCHAR2(40)
 ,TAX_ADDR2                         VARCHAR2(50)
 ,TAX_CITY                          VARCHAR2(30)
 ,TAX_STATE                         VARCHAR2(2)
 ,TAX_ZIP                           VARCHAR2(5)
 ,TAX_TEN_CODE                      VARCHAR2(4)
 ,TAX_OCCUPIED                      VARCHAR2(1)
 ,TAX_LEGAL_DESC                    VARCHAR2(200)
 ,UMS_LAST_NAME                     VARCHAR2(40)
 ,UMS_FIRST_NAME                    VARCHAR2(40)
 ,UMS_DRIVERS_LIC                   VARCHAR2(20)
 ,UMS_BIRTH_DATE                    VARCHAR2(10)
 ,INTERSECTION1                     VARCHAR2(40)
 ,INTERSECTION2                     VARCHAR2(40)
 ,PARCEL_ID                         VARCHAR2(11)
 ,STREET_ID                         VARCHAR2(6)
 ,BLOCK_ID                          NUMBER(8,0)
 ,ROAD_ID                           NUMBER(8,0)
 ,INTERSECT_ID1                     VARCHAR2(20)
 ,INTERSECT_ID2                     VARCHAR2(20)
 ,TAX_ID                            VARCHAR2(25)
 ,UMS_ID                            NUMBER(8,0)
 ,RECORD_SEQ                        VARCHAR2(20)
  )  tablespace GIS_DATA  nologging
  ;

--drop   table GARLAND.CCS_ADDRESSES_TEST_MAKE;
  create table GARLAND.CCS_ADDRESSES_TEST_MAKE  (
  ADDRESS_ID                        NUMBER(22)
 ,ADDR_BLOCK                        NUMBER(22)
 ,ADDR_NUMBER                       NUMBER(8,0)
 ,ADDR_PREFIX                       VARCHAR2(2)
 ,ADDR_NAME                         VARCHAR2(30)
 ,ADDR_TYPE                         VARCHAR2(4)
 ,ADDR_SUFFIX                       VARCHAR2(2)
 ,ADDR_BLDG                         VARCHAR2(20)
 ,ADDR_UNIT                         VARCHAR2(20)
 ,ADDR_CITY                         VARCHAR2(13)
 ,ADDR_ZIP                          VARCHAR2(5)
 ,ADDR_TEN_CODE                     VARCHAR2(34)
 ,COUNCIL_DIST                      NUMBER(1,0)
 ,INSPECTOR_DIST                    NUMBER(22)
 ,POLICE_BEAT                       NUMBER(3,0)
 ,TAX_ACCOUNT                       VARCHAR2(10)
 ,TAX_DCAD                          VARCHAR2(25)
 ,TAX_PROP_TYPE                     VARCHAR2(1)
 ,TAX_ZONING_CODE                   VARCHAR2(10)
 ,TAX_EXEMPTION                     VARCHAR2(12)
 ,TAX_DEED_CHNG_DATE                VARCHAR2(10)
 ,TAX_OWNER                         VARCHAR2(81)
 ,TAX_ADDR1                         VARCHAR2(40)
 ,TAX_ADDR2                         VARCHAR2(50)
 ,TAX_CITY                          VARCHAR2(30)
 ,TAX_STATE                         VARCHAR2(2)
 ,TAX_ZIP                           VARCHAR2(5)
 ,TAX_TEN_CODE                      VARCHAR2(4)
 ,TAX_OCCUPIED                      VARCHAR2(1)
 ,TAX_LEGAL_DESC                    VARCHAR2(200)
 ,UMS_LAST_NAME                     VARCHAR2(40)
 ,UMS_FIRST_NAME                    VARCHAR2(40)
 ,UMS_DRIVERS_LIC                   VARCHAR2(20)
 ,UMS_BIRTH_DATE                    VARCHAR2(10)
 ,INTERSECTION1                     VARCHAR2(40)
 ,INTERSECTION2                     VARCHAR2(40)
 ,PARCEL_ID                         VARCHAR2(11)
 ,STREET_ID                         VARCHAR2(0)
 ,BLOCK_ID                          NUMBER(22)
 ,ROAD_ID                           NUMBER(22)
 ,INTERSECT_ID1                     VARCHAR2(20)
 ,INTERSECT_ID2                     VARCHAR2(20)
 ,TAX_ID                            NUMBER(8,0)
 ,UMS_ID                            NUMBER(8,0)
 ,RECORD_SEQ                        NUMBER(22)
 ,PARCEL_ID_NEW                     NUMBER(7,0)
 ,ADDRESS_TYPE                      VARCHAR2(20)
  )  tablespace GIS_DATA  nologging
  ;

--drop   table GARLAND.CCS_ADDRESS_COPY;
  create table GARLAND.CCS_ADDRESS_COPY  (
  ADDRESS_ID                        NUMBER(8,0)
 ,ADDR_BLOCK                        NUMBER(8,0)
 ,ADDR_NUMBER                       NUMBER(8,0)
 ,ADDR_PREFIX                       VARCHAR2(2)
 ,ADDR_NAME                         VARCHAR2(30)
 ,ADDR_TYPE                         VARCHAR2(4)
 ,ADDR_SUFFIX                       VARCHAR2(2)
 ,ADDR_BLDG                         VARCHAR2(20)
 ,ADDR_UNIT                         VARCHAR2(20)
 ,ADDR_CITY                         VARCHAR2(15)
 ,ADDR_ZIP                          VARCHAR2(5)
 ,ADDR_TEN_CODE                     VARCHAR2(4)
 ,COUNCIL_DIST                      VARCHAR2(1)
 ,INSPECTOR_DIST                    VARCHAR2(2)
 ,POLICE_BEAT                       NUMBER(3,0)
 ,TAX_ACCOUNT                       VARCHAR2(25)
 ,TAX_DCAD                          VARCHAR2(25)
 ,TAX_PROP_TYPE                     VARCHAR2(1)
 ,TAX_ZONING_CODE                   VARCHAR2(10)
 ,TAX_EXEMPTION                     VARCHAR2(12)
 ,TAX_DEED_CHNG_DATE                VARCHAR2(10)
 ,TAX_OWNER                         VARCHAR2(100)
 ,TAX_ADDR1                         VARCHAR2(50)
 ,TAX_ADDR2                         VARCHAR2(50)
 ,TAX_CITY                          VARCHAR2(30)
 ,TAX_STATE                         VARCHAR2(2)
 ,TAX_ZIP                           VARCHAR2(5)
 ,TAX_TEN_CODE                      VARCHAR2(4)
 ,TAX_OCCUPIED                      VARCHAR2(1)
 ,TAX_LEGAL_DESC                    VARCHAR2(200)
 ,UMS_LAST_NAME                     VARCHAR2(40)
 ,UMS_FIRST_NAME                    VARCHAR2(40)
 ,UMS_DRIVERS_LIC                   VARCHAR2(20)
 ,UMS_BIRTH_DATE                    VARCHAR2(10)
 ,INTERSECTION1                     VARCHAR2(40)
 ,INTERSECTION2                     VARCHAR2(40)
 ,PARCEL_ID                         VARCHAR2(11)
 ,STREET_ID                         VARCHAR2(6)
 ,BLOCK_ID                          NUMBER(10,0)
 ,ROAD_ID                           NUMBER(8,0)
 ,INTERSECT_ID1                     VARCHAR2(20)
 ,INTERSECT_ID2                     VARCHAR2(20)
 ,TAX_ID                            VARCHAR2(25)
 ,UMS_ID                            NUMBER(8,0)
 ,RECORD_SEQ                        NUMBER(10,0)
 ,PARCEL_ID_NEW                     NUMBER(8,0)
  )  tablespace GIS_DATA  nologging
  ;

--drop   table GARLAND.CCS_ADDRESS_TEST;
  create table GARLAND.CCS_ADDRESS_TEST  (
  ADDRESS_ID                        NUMBER(8,0)
 ,ADDR_BLOCK                        NUMBER(8,0)
 ,ADDR_NUMBER                       NUMBER(8,0)
 ,ADDR_PREFIX                       VARCHAR2(2)
 ,ADDR_NAME                         VARCHAR2(30)
 ,ADDR_TYPE                         VARCHAR2(4)
 ,ADDR_SUFFIX                       VARCHAR2(2)
 ,ADDR_BLDG                         VARCHAR2(20)
 ,ADDR_UNIT                         VARCHAR2(20)
 ,ADDR_CITY                         VARCHAR2(15)
 ,ADDR_ZIP                          VARCHAR2(5)
 ,ADDR_TEN_CODE                     VARCHAR2(4)
 ,COUNCIL_DIST                      VARCHAR2(1)
 ,INSPECTOR_DIST                    VARCHAR2(2)
 ,POLICE_BEAT                       NUMBER(3,0)
 ,TAX_ACCOUNT                       VARCHAR2(25)
 ,TAX_DCAD                          VARCHAR2(25)
 ,TAX_PROP_TYPE                     VARCHAR2(1)
 ,TAX_ZONING_CODE                   VARCHAR2(10)
 ,TAX_EXEMPTION                     VARCHAR2(12)
 ,TAX_DEED_CHNG_DATE                VARCHAR2(10)
 ,TAX_OWNER                         VARCHAR2(100)
 ,TAX_ADDR1                         VARCHAR2(50)
 ,TAX_ADDR2                         VARCHAR2(50)
 ,TAX_CITY                          VARCHAR2(30)
 ,TAX_STATE                         VARCHAR2(2)
 ,TAX_ZIP                           VARCHAR2(5)
 ,TAX_TEN_CODE                      VARCHAR2(4)
 ,TAX_OCCUPIED                      VARCHAR2(1)
 ,TAX_LEGAL_DESC                    VARCHAR2(200)
 ,UMS_LAST_NAME                     VARCHAR2(40)
 ,UMS_FIRST_NAME                    VARCHAR2(40)
 ,UMS_DRIVERS_LIC                   VARCHAR2(20)
 ,UMS_BIRTH_DATE                    VARCHAR2(10)
 ,INTERSECTION1                     VARCHAR2(40)
 ,INTERSECTION2                     VARCHAR2(40)
 ,PARCEL_ID                         VARCHAR2(11)
 ,STREET_ID                         VARCHAR2(6)
 ,BLOCK_ID                          NUMBER(8,0)
 ,ROAD_ID                           NUMBER(8,0)
 ,INTERSECT_ID1                     VARCHAR2(20)
 ,INTERSECT_ID2                     VARCHAR2(20)
 ,TAX_ID                            VARCHAR2(25)
 ,UMS_ID                            NUMBER(8,0)
 ,RECORD_SEQ                        NUMBER(10,0)
 ,PARCEL_ID_NEW                     NUMBER(8,0)
 ,ADDRESS_TYPE                      VARCHAR2(20)
  )  tablespace GIS_DATA  nologging
  ;


