

--	EXAMINE A TEXT AND REPLACE EACH NON-DISPLAYABLE BYTE WITH A SPACE.
--	REPLACE CONSECUTIVE SPACES WITH A SINGLE SPACE.
--	REMOVE LEADING AND TRAILING SPACES.


CREATE OR REPLACE FUNCTION	garland.ADR_STRING_CLEANER 
					(OLD_TEXT		VARCHAR2)

					  RETURN		VARCHAR2
AS

	NEW_TEXT		VARCHAR2(2000);
	WORK_TEXT		VARCHAR2(2000);

	COUNT_SPACE		NUMBER(04);

	BYTE			CHAR(01);

	VALID_BYTES		VARCHAR2(100);

BEGIN

	VALID_BYTES	:= 'ABCDEFGHIJKLMNOPQRSTUVWXYZ 0123456789';
	VALID_BYTES	:=  VALID_BYTES || '''"-,.;:/()?!@#$%^&*`~_=+\|[{]}<>';
	VALID_BYTES	:=  VALID_BYTES || 'abcdefghijklmnopqrstuvwxyz';

	WORK_TEXT	:=  NVL (OLD_TEXT, ' ');
	NEW_TEXT 	:= ' ';

	COUNT_SPACE	:= 0;

	FOR	X IN	01..LENGTH (WORK_TEXT)
	LOOP

		BYTE	:= SUBSTR (WORK_TEXT, X, 01);

		IF	INSTR (VALID_BYTES, BYTE) = 0		THEN
			BYTE	:= ' ';
		END IF;
			
		IF	BYTE > ' '					
		OR	COUNT_SPACE  = 00				THEN
			NEW_TEXT := NEW_TEXT || BYTE;
		END IF;

		IF	BYTE = ' '					THEN
			COUNT_SPACE := 01;
		ELSE
			COUNT_SPACE := 00;
		END IF;

	END LOOP;

	RETURN 	LTRIM (RTRIM (NEW_TEXT));

END;

