
	DROP TABLE		US_STATES;

	CREATE TABLE	US_STATES
	(
		ABBRV		VARCHAR2(02),
		NAME		VARCHAR2(20)
	)

		PCTFREE	05	PCTUSED	20	

		STORAGE	(INITIAL	1K	NEXT	1K)
	;


	INSERT INTO	US_STATES	VALUES	( 'AL', 'ALABAMA'); 
	INSERT INTO	US_STATES	VALUES	( 'AK', 'ALASKA'); 
	INSERT INTO	US_STATES	VALUES	( 'AZ', 'ARIZONA'); 
	INSERT INTO	US_STATES	VALUES	( 'AR', 'ARKANSAS'); 
	INSERT INTO	US_STATES	VALUES	( 'CA', 'CALIFORNIA'); 
	INSERT INTO	US_STATES	VALUES	( 'CO', 'COLORADO'); 
	INSERT INTO	US_STATES	VALUES	( 'CT', 'CONNECTICUT'); 
	INSERT INTO	US_STATES	VALUES	( 'DE', 'DELAWARE'); 
	INSERT INTO	US_STATES	VALUES	( 'DC', 'DISTRICT OF COLUMBIA'); 
	INSERT INTO	US_STATES	VALUES	( 'FL', 'FLORIDA'); 
	INSERT INTO	US_STATES	VALUES	( 'GA', 'GEORGIA'); 
	INSERT INTO	US_STATES	VALUES	( 'HI', 'HAWAII'); 
	INSERT INTO	US_STATES	VALUES	( 'ID', 'IDAHO'); 
	INSERT INTO	US_STATES	VALUES	( 'IL', 'ILLINOIS'); 
	INSERT INTO	US_STATES	VALUES	( 'IN', 'INDIANA'); 
	INSERT INTO	US_STATES	VALUES	( 'IA', 'IOWA'); 
	INSERT INTO	US_STATES	VALUES	( 'KS', 'KANSAS'); 
	INSERT INTO	US_STATES	VALUES	( 'KY', 'KENTUCKY'); 
	INSERT INTO	US_STATES	VALUES	( 'LA', 'LOUISIANA'); 
	INSERT INTO	US_STATES	VALUES	( 'ME', 'MAINE'); 
	INSERT INTO	US_STATES	VALUES	( 'MA', 'MASSACHUSETTS'); 
	INSERT INTO	US_STATES	VALUES	( 'MD', 'MARYLAND'); 
	INSERT INTO	US_STATES	VALUES	( 'MI', 'MICHIGAN'); 
	INSERT INTO	US_STATES	VALUES	( 'MN', 'MINNESOTA'); 
	INSERT INTO	US_STATES	VALUES	( 'MS', 'MISSISSIPPI'); 
	INSERT INTO	US_STATES	VALUES	( 'MO', 'MISSOURI'); 
	INSERT INTO	US_STATES	VALUES	( 'MT', 'MONTANA'); 
	INSERT INTO	US_STATES	VALUES	( 'NB', 'NEBRASKA'); 
	INSERT INTO	US_STATES	VALUES	( 'NV', 'NEVADA'); 
	INSERT INTO	US_STATES	VALUES	( 'NH', 'NEW HAMPSHIRE'); 
	INSERT INTO	US_STATES	VALUES	( 'NJ', 'NEW JERSEY'); 
	INSERT INTO	US_STATES	VALUES	( 'NM', 'NEW MEXICO'); 
	INSERT INTO	US_STATES	VALUES	( 'NY', 'NEW YORK'); 
	INSERT INTO	US_STATES	VALUES	( 'NC', 'NORTH CAROLINA'); 
	INSERT INTO	US_STATES	VALUES	( 'ND', 'NORTH DAKOTA'); 
	INSERT INTO	US_STATES	VALUES	( 'OH', 'OHIO'); 
	INSERT INTO	US_STATES	VALUES	( 'OK', 'OKLAHOMA'); 
	INSERT INTO	US_STATES	VALUES	( 'OR', 'OREGON'); 
	INSERT INTO	US_STATES	VALUES	( 'PA', 'PENNSYLVANIA'); 
	INSERT INTO	US_STATES	VALUES	( 'RI', 'RHODE ISLAND'); 
	INSERT INTO	US_STATES	VALUES	( 'SC', 'SOUTH CAROLINA'); 
	INSERT INTO	US_STATES	VALUES	( 'SD', 'SOUTH DAKOTA'); 
	INSERT INTO	US_STATES	VALUES	( 'TN', 'TENNESSEE'); 
	INSERT INTO	US_STATES	VALUES	( 'TX', 'TEXAS'); 
	INSERT INTO	US_STATES	VALUES	( 'UT', 'UTAH'); 
	INSERT INTO	US_STATES	VALUES	( 'VT', 'VERMONT'); 
	INSERT INTO	US_STATES	VALUES	( 'VA', 'VIRGINIA'); 
	INSERT INTO	US_STATES	VALUES	( 'WA', 'WASHINGTON'); 
	INSERT INTO	US_STATES	VALUES	( 'WV', 'WEST VIRGINIA'); 
	INSERT INTO	US_STATES	VALUES	( 'WI', 'WISCONSIN'); 
	INSERT INTO	US_STATES	VALUES	( 'WY', 'WYOMING'); 


