                                                                                                                                                  
--------------------------------------------------------------------------------------------------------------------------------------------------
insert into adrAlias_vw values ('*', '%CASA RIDGE%',          '*','*',       0,999999,      '', '',                       '', '',        '221');  
insert into adrAlias_vw values ('*', 'BRESSEE',               '*','*',       0,999999,      '', '',                       '', '',        '221');  
insert into adrAlias_vw values ('*', 'CALEO',                 '*','*',       0,999999,      '', '',                       '', '',        '221');  
insert into adrAlias_vw values ('*', 'CAPSTONE',              '*','*',       0,999999,      '', '',                       '', '',        '221');  
insert into adrAlias_vw values ('*', 'CASA RIDGE',            '*','*',       0,999999,      '', '',                       '', '',        '221');  
insert into adrAlias_vw values ('*', 'CHATSWORTH',            'DR','*',      0,999999,      '', '',                       '', '',        '221');  
insert into adrAlias_vw values ('*', 'CHESAPEAKE',            'CT','*',      0,999999,      '', '',                       '', '',        '221');  
insert into adrAlias_vw values ('*', 'COUNTRY MANOR',         '*','*',       0,999999,      '', '',                       '', '',        '221');  
insert into adrAlias_vw values ('*', 'DERBY RN',              '*','*',       0,999999,      '', '',                       '', '',        '221');  
insert into adrAlias_vw values ('*', 'EMERALD',               '*','*',       0,999999,      '', '',                       '', '',        '221');  
insert into adrAlias_vw values ('*', 'FOREST CLIFF',          'DR','*',      0,999999,      '', '',                       '', '',        '221');  
insert into adrAlias_vw values ('*', 'HARLINGTON',            'LN','*',      0,999999,      '', '',                       '', '',        '221');  
insert into adrAlias_vw values ('*', 'HOLLOW RIDGE',          'RD','*',      0,999999,      '', '',                       '', '',        '221');  
insert into adrAlias_vw values ('*', 'LOCHLYN',               '*','*',       0,999999,      '', '',                       '', '',        '221');  
insert into adrAlias_vw values ('*', 'LOS RIOS',              'DR','*',      0,999999,      '', '',                       '', '',        '221');  
insert into adrAlias_vw values ('*', 'PINECREEK',             '*','*',       0,999999,      '', '',                       '', '',        '221');  
insert into adrAlias_vw values ('*', 'PRAIRIE',               'CIR','*',     0,999999,      '', '',                       '', '',        '221');  
insert into adrAlias_vw values ('*', 'RIVERWAY',              'CT','*',      0,999999,      '', '',                       '', '',        '221');  
insert into adrAlias_vw values ('*', 'SALZBURG',              '*','*',       0,999999,      '', '',                       '', '',        '221');  
insert into adrAlias_vw values ('*', 'SAN DIEGO',             'DR','*',      0,999999,      '', '',                       '', '',        '221');  
insert into adrAlias_vw values ('*', 'SANTA TERESA',          'AVE','*',     0,999999,      '', '',                       '', '',        '221');  
insert into adrAlias_vw values ('*', 'SEAFIELD',              '*','*',       0,999999,      '', '',                       '', '',        '221');  
insert into adrAlias_vw values ('*', 'SON',                   '*','*',       0,999999,      '', '',                       '', '',        '221');  
insert into adrAlias_vw values ('*', 'SOUTHRIDGE',            'DR','*',      0,999999,      '', '',                       '', '',        '221');  
insert into adrAlias_vw values ('*', 'SPRINGTREE',            '*','*',       0,999999,      '', '',                       '', '',        '221');  
insert into adrAlias_vw values ('*', 'WINDJAMMER',            '*','*',       0,999999,      '', '',                       '', '',        '221');  
insert into adrAlias_vw values ('S', '5TH STREET',            'CIR','*',     0,999999,      'S', 'FIFTH',                 'CIR', '',     '23');   
insert into adrAlias_vw values ('*', 'CROSS',                 'CT','*',      0,999999,      '', 'CROSS COURTS',           'DR', '',      '23');   
insert into adrAlias_vw values ('*', 'JOANN',                 '*','*',       0,999999,      '', 'JO ANN',                 '', '',        '23');   
insert into adrAlias_vw values ('*', 'NOVEL CIRL',            '*','*',       0,999999,      '', 'NOVEL',                  'CIR', '',     '23');   
insert into adrAlias_vw values ('*', 'SPINDRIFT',             '*','*',       0,999999,      '', 'SPINDRIFT PASSAGE',      '', '',        '23');   
insert into adrAlias_vw values ('*', 'A AVE',                 '*','*',       0,999999,      '', 'AVENUE A',               ' ', '',       'AVE');  
insert into adrAlias_vw values ('*', 'AVE A',                 '*','*',       0,999999,      '', 'AVENUE A',               ' ', '',       'AVE');  
insert into adrAlias_vw values ('*', 'AVE B',                 '*','*',       0,999999,      '', 'AVENUE B',               ' ', '',       'AVE');  
insert into adrAlias_vw values ('*', 'AVE C',                 '*','*',       0,999999,      '', 'AVENUE C',               ' ', '',       'AVE');  
insert into adrAlias_vw values ('*', 'AVE D',                 '*','*',       0,999999,      '', 'AVENUE D',               ' ', '',       'AVE');  
insert into adrAlias_vw values ('*', 'AVE E',                 '*','*',       0,999999,      '', 'AVENUE E',               ' ', '',       'AVE');  
insert into adrAlias_vw values ('*', 'AVE F',                 '*','*',       0,999999,      '', 'AVENUE F',               ' ', '',       'AVE');  
insert into adrAlias_vw values ('*', 'AVE G',                 '*','*',       0,999999,      '', 'AVENUE G',               ' ', '',       'AVE');  
insert into adrAlias_vw values ('*', 'AVENUE E',              '*','*',       0,999999,      '', 'AVENUE E',               ' ', '',       'AVE');  
insert into adrAlias_vw values ('*', 'B AVE',                 '*','*',       0,999999,      '', 'AVENUE B',               ' ', '',       'AVE');  
insert into adrAlias_vw values ('*', 'C AVE',                 '*','*',       0,999999,      '', 'AVENUE C',               ' ', '',       'AVE');  
insert into adrAlias_vw values ('*', 'D AVE',                 '*','*',       0,999999,      '', 'AVENUE D',               ' ', '',       'AVE');  
insert into adrAlias_vw values ('*', 'F AVE',                 '*','*',       0,999999,      '', 'AVENUE F',               ' ', '',       'AVE');  
insert into adrAlias_vw values ('*', 'G AVE',                 '*','*',       0,999999,      '', 'AVENUE G',               ' ', '',       'AVE');  
insert into adrAlias_vw values ('*', '%190',                  '*','*',       0,999999,      '', 'GEORGE BUSH',            'HWY', '',     'LIKE'); 
insert into adrAlias_vw values ('*', '%66',                   '*','*',       0,999999,      '', 'STATE HIGHWAY 66',       'HWY', '',     'LIKE'); 
insert into adrAlias_vw values ('*', '%78',                   '*','*',       0,999999,      '', 'LAVON',                  'DR', '',      'LIKE'); 
insert into adrAlias_vw values ('*', '% BOX %',               '*','*',       0,999999,      '', '',                       '', '',        'LIKE/');
insert into adrAlias_vw values ('*', '%DALLAS%',              '*','*',       0,999999,      '', '',                       '', '',        'LIKE/');
insert into adrAlias_vw values ('*', '%MESQUITE%',            '*','*',       0,999999,      '', '',                       '', '',        'LIKE/');
insert into adrAlias_vw values ('*', '%RICHARDSON%',          '*','*',       0,999999,      '', '',                       '', '',        'LIKE/');
insert into adrAlias_vw values ('*', '%SACHSE%',              '*','*',       0,999999,      '', '',                       '', '',        'LIKE/');
insert into adrAlias_vw values ('*', '%SUNNYVALE%',           '*','*',       0,999999,      '', '',                       '', '',        'LIKE/');
insert into adrAlias_vw values ('*', '%WYLIE%',               '*','*',       0,999999,      '', '',                       '', '',        'LIKE/');
insert into adrAlias_vw values ('*', 'GALAXY',                '*','*',       0,999999,      '', 'GALAXIE',                '', '',        'MISC'); 
insert into adrAlias_vw values ('*', 'LAKE RAY HUBBARD',      '*','*',       0,999999,      '', 'LAKE HUBBARD',           '', '',        'MISC'); 
insert into adrAlias_vw values ('*', 'LYNDA',                 '*','*',       0,999999,      '', 'LINDA',                  '', '',        'MISC'); 
insert into adrAlias_vw values ('*', 'NW',                    '*','*',       0,999999,      '', 'NORTHWEST',              '', '',        'MISC'); 
insert into adrAlias_vw values ('*', 'OATS',                  '*','*',       0,999999,      '', 'OATES',                  '', '',        'MISC'); 
insert into adrAlias_vw values ('*', 'PLACE 1',               '*','*',       0,999999,      '', 'PLACE ONE',              '', '',        'MISC'); 
insert into adrAlias_vw values ('*', 'TRINID',                '*','*',       0,999999,      '', 'TRINIDAD',               '', '',        'MISC'); 
insert into adrAlias_vw values ('*', 'HARKNESS',              'DR','*',      0,999999,      '', '',                       '', '',        'N1$');  
insert into adrAlias_vw values ('*', 'OAK HOLLOW',            'DR','*',      0,999999,      '', '',                       '', '',        'N1$');  
insert into adrAlias_vw values ('*', 'CLUB GLEN',             '*','*',       0,999999,      '', 'CLUB GLEN',              '', '',        'NAME$');
insert into adrAlias_vw values ('*', 'LYONS CREST',           '*','*',       0,999999,      '', 'LYONS CREST',            '', '',        'NAME$');
insert into adrAlias_vw values ('*', 'MACGREGOR',             '*','*',       0,999999,      '', 'MACGREGOR',              '', '',        'NAME$');
insert into adrAlias_vw values ('*', 'SAVAGE',                '*','*',       0,999999,      '', 'SAVAGE',                 '', '',        'NAME$');
insert into adrAlias_vw values ('*', '1',                     '*','*',       0,999999,      '', 'FIRST',                  'ST', ' ',     'NTH');  
insert into adrAlias_vw values ('*', '10',                    '*','*',       0,999999,      '', 'TENTH',                  'ST', ' ',     'NTH');  
insert into adrAlias_vw values ('*', '10TH',                  '*','*',       0,999999,      '', 'TENTH',                  'ST', ' ',     'NTH');  
insert into adrAlias_vw values ('*', '11',                    '*','*',       0,999999,      '', 'ELEVENTH',               'ST', ' ',     'NTH');  
insert into adrAlias_vw values ('*', '11TH',                  '*','*',       0,999999,      '', 'ELEVENTH',               'ST', ' ',     'NTH');  
insert into adrAlias_vw values ('*', '12',                    '*','*',       0,999999,      '', 'TWELFTH',                'ST', ' ',     'NTH');  
insert into adrAlias_vw values ('*', '12TH',                  '*','*',       0,999999,      '', 'TWELFTH',                'ST', ' ',     'NTH');  
insert into adrAlias_vw values ('*', '13',                    '*','*',       0,999999,      '', 'THIRTEENTH',             'ST', ' ',     'NTH');  
insert into adrAlias_vw values ('*', '13TH',                  '*','*',       0,999999,      '', 'THIRTEENTH',             'ST', ' ',     'NTH');  
insert into adrAlias_vw values ('*', '15',                    '*','*',       0,999999,      '', 'FIFTEENTH',              'ST', ' ',     'NTH');  
insert into adrAlias_vw values ('*', '15TH',                  '*','*',       0,999999,      '', 'FIFTEENTH',              'ST', ' ',     'NTH');  
insert into adrAlias_vw values ('*', '16',                    '*','*',       0,999999,      '', 'SIXTEENTH',              'ST', ' ',     'NTH');  
insert into adrAlias_vw values ('*', '16TH',                  '*','*',       0,999999,      '', 'SIXTEENTH',              'ST', ' ',     'NTH');  
insert into adrAlias_vw values ('*', '17',                    '*','*',       0,999999,      '', 'SEVENTEENTH',            'ST', ' ',     'NTH');  
insert into adrAlias_vw values ('*', '17TH',                  '*','*',       0,999999,      '', 'SEVENTEENTH',            'ST', ' ',     'NTH');  
insert into adrAlias_vw values ('*', '1ST',                   '*','*',       0,999999,      '', 'FIRST',                  'ST', ' ',     'NTH');  
insert into adrAlias_vw values ('*', '2',                     '*','*',       0,999999,      '', 'SECOND',                 'ST', ' ',     'NTH');  
insert into adrAlias_vw values ('*', '2ND',                   '*','*',       0,999999,      '', 'SECOND',                 'ST', ' ',     'NTH');  
insert into adrAlias_vw values ('*', '3',                     '*','*',       0,999999,      '', 'THIRD',                  'ST', ' ',     'NTH');  
insert into adrAlias_vw values ('*', '3RD',                   '*','*',       0,999999,      '', 'THIRD',                  'ST', ' ',     'NTH');  
insert into adrAlias_vw values ('*', '4',                     '*','*',       0,999999,      '', 'FOURTH',                 'ST', ' ',     'NTH');  
insert into adrAlias_vw values ('*', '4TH',                   '*','*',       0,999999,      '', 'FOURTH',                 'ST', ' ',     'NTH');  
insert into adrAlias_vw values ('*', '5',                     '*','*',       0,999999,      '', 'FIFTH',                  'ST', ' ',     'NTH');  
insert into adrAlias_vw values ('*', '5TH',                   '*','*',       0,999999,      '', 'FIFTH',                  'ST', ' ',     'NTH');  
insert into adrAlias_vw values ('*', '6',                     '*','*',       0,999999,      '', 'SIXTH',                  'ST', ' ',     'NTH');  
insert into adrAlias_vw values ('*', '6TH',                   '*','*',       0,999999,      '', 'SIXTH',                  'ST', ' ',     'NTH');  
insert into adrAlias_vw values ('*', '7',                     '*','*',       0,999999,      '', 'SEVENTH',                'ST', ' ',     'NTH');  
insert into adrAlias_vw values ('*', '7TH',                   '*','*',       0,999999,      '', 'SEVENTH',                'ST', ' ',     'NTH');  
insert into adrAlias_vw values ('*', '8',                     '*','*',       0,999999,      '', 'EIGHTH',                 'ST', ' ',     'NTH');  
insert into adrAlias_vw values ('*', '8TH',                   '*','*',       0,999999,      '', 'EIGHTH',                 'ST', ' ',     'NTH');  
insert into adrAlias_vw values ('*', '9',                     '*','*',       0,999999,      '', 'NINTH',                  'ST', ' ',     'NTH');  
insert into adrAlias_vw values ('*', '9TH',                   '*','*',       0,999999,      '', 'NINTH',                  'ST', ' ',     'NTH');  
insert into adrAlias_vw values ('*', 'STATE',                 'HWY','*',     0,999999,      '', 'STATE HIGHWAY',          '', '',        'PART*');
insert into adrAlias_vw values ('*', 'WALNUT',                'CIR','*',     0,999999,      '', 'WALNUT CIRCLE',          ' ', '',       'PART*');
insert into adrAlias_vw values ('E', 'GARLAND',               '*','*',       200,699,       'E', 'AVENUE B',              ' ', '',       'PAST'); 
insert into adrAlias_vw values ('E', 'GARLAND',               '*','*',       700,1099,      '', 'STATE HIGHWAY 66',       'HWY', '',     'PAST'); 
insert into adrAlias_vw values ('E', 'GARLAND',               '*','*',       1100,2399,     '', 'COMMERCE',               'ST ', '',     'PAST'); 
insert into adrAlias_vw values ('W', 'GARLAND',               '*','*',       100,1399,      '', 'MAIN',                   'ST', '',      'PAST'); 
insert into adrAlias_vw values ('*', 'NORTH STAR',            '*','*',       0,999999,      'N', 'GARLAND',               'AVE', '',     'PAST'); 
insert into adrAlias_vw values ('*', 'MILLER',                'PK','N',      0,999999,      '', 'MILLER PARK NORTH',      ' ', ' ',      'PULL'); 
insert into adrAlias_vw values ('*', 'MILLER',                'PK','S',      0,999999,      '', 'MILLER PARK SOUTH',      ' ', ' ',      'PULL'); 
insert into adrAlias_vw values ('N', 'MILLER',                'PK',' ',      0,999999,      '', 'MILLER PARK NORTH',      ' ', ' ',      'PULL'); 
insert into adrAlias_vw values ('S', 'MILLER',                'PK',' ',      0,999999,      '', 'MILLER PARK SOUTH',      ' ', ' ',      'PULL'); 
insert into adrAlias_vw values ('N', 'MILLER PARK',           ' ',' ',       0,999999,      '', 'MILLER PARK NORTH',      ' ', ' ',      'PULL'); 
insert into adrAlias_vw values ('S', 'MILLER PARK',           ' ',' ',       0,999999,      '', 'MILLER PARK SOUTH',      ' ', ' ',      'PULL'); 
insert into adrAlias_vw values ('*', 'WALNUT',                'CIR','E',     0,999999,      '', 'WALNUT CIRCLE EAST',     ' ', ' ',      'PULL'); 
insert into adrAlias_vw values ('*', 'WALNUT',                'CIR','W',     0,999999,      '', 'WALNUT CIRCLE WEST',     ' ', ' ',      'PULL'); 
insert into adrAlias_vw values ('E', 'WALNUT',                'CIR',' ',     0,999999,      '', 'WALNUT CIRCLE EAST',     ' ', ' ',      'PULL'); 
insert into adrAlias_vw values ('W', 'WALNUT',                'CIR',' ',     0,999999,      '', 'WALNUT CIRCLE WEST',     ' ', ' ',      'PULL'); 
insert into adrAlias_vw values ('E', 'WALNUT CIRCLE',         ' ',' ',       0,999999,      '', 'WALNUT CIRCLE EAST',     ' ', ' ',      'PULL'); 
insert into adrAlias_vw values ('W', 'WALNUT CIRCLE',         ' ',' ',       0,999999,      '', 'WALNUT CIRCLE WEST',     ' ', ' ',      'PULL'); 
/*                                                                                                                                                
120 rows selected.
             
-------------
*/
commit;
/*
1 row selected.
